[package]
name = "rc4-aes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
rust-crypto = "0.2"
aes = "0.8"
